baseURL = 'https://yanagiis.github.io/'
languageCode = 'en-us'
title = "JimmyOu's notes"
theme = 'PaperMod'

[author]
  name = "JimmyOu"
  copyright = "2022 JimmyOu"

[menu]
  main = [
    { name = "Home", url = "/" },
    { name = "About", url = "/about" }
  ]

[params]
  description = "Note everything here"
  subtitleLength = 25
